services:
  - type: web
    name: pinball-strategy
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    branch: main
    pullRequestPreviewsEnabled: false
    envVars:
      - key: PORT
        value: "10000"
